import numpy as np
func = input(f"Input rock, paper or scissors:")  #ask the user for input 
RPS = np.array(['rock', 'paper', 'scissors'])  #an array of the possibilities
indx = np.random.randint(0, len(RPS), 1)  #the program picks one index from the array
print(f"The programme picked:", RPS[indx],"")  #print what is associated to the index generated by the programme
if RPS[indx] == func:  #result if user and programme input the same value 
    print(f"tie" ) 
elif RPS[indx] == "rock" and func == "paper":  #results if the player wins
    print(f"You win")
elif RPS[indx] == "scissors" and func == "rock":
    print(f"You win") 
elif RPS[indx] == "paper" and func == "scissors":
    print(f"You win")
else:
    print(f"You lose")  